### ISSUE TITLE
More customization

### ISSUE THREAD

**Issue by rezafaraji93** [hasin-neobank/android-persian-picker#3]
Thanks for this great library. It would be better if you add more customizations to the composables like button color, border, size and etc. Also I wish I could get the current selected date live update, not just buy pressing the button.

**Comment by fatemeh-afshari** [comment]
Such a customizations are not critical. You can add them on your own project. Thanks

**Comment by rezafaraji93** [comment]
Yes these customizations are not critical but as I mentioned it will be nice to have! And would you please guide me to have my custom button with this library?
